name: Java CI on Windows

# Trigger workflow on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # 3️⃣ Build with Maven wrapper
    - name: Build project with Maven
      run: mvnw.cmd clean install

    # 4️⃣ Optional: Run tests
    - name: Run unit tests
      run: mvnw.cmd test
